# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

parameters:
  - name: pluginOrganization
    displayName: Description of pluginOrganization
    default: someTextpluginOrganization
    type: string

  - name: pluginProject
    displayName: Description of pluginProject
    default: someTextpluginProject
    type: string

  - name: pluginName
    displayName: Description of pluginName
    default: someTextpluginName
    type: string

  - name: pluginPath
    displayName: Description of pluginPath
    default: someTextpluginPath
    type: string

  - name: pluginType
    displayName: Description of pluginType
    default: someTextpluginType
    type: string

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: CmdLine@2
  inputs:
    script: |
      echo 'The value of pluginOrganization:' ${{ parameters.pluginOrganization }}
      echo 'The value of pluginProject:'  ${{ parameters.pluginProject }}
      echo 'The value of pluginName:'  ${{ parameters.pluginName }}
      echo 'The value of pluginPath:'  ${{ parameters.pluginPath }}
      echo 'The value of pluginType:'  ${{ parameters.pluginType }}