# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- name: pluginOrganization
- name: pluginProject
- name: pluginName
- name: pluginPath

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
- script: echo pluginOrganization = $(pluginOrganization)
  displayName: 'echo pluginOrganization'
- script: echo pluginProject = $(pluginProject)
  displayName: 'echo pluginProject'
- script: echo pluginName = $(pluginName)
  displayName: 'echo pluginName'
- script: echo pluginPath = $(pluginPath)
  displayName: 'echo pluginPath'
